name: AeonFree
subname: Free Web Hosting with PHP, MySQL and cPanel
description: Get Free Web Hosting with Unlimited Disk Space, Unlimited Bandwidth and Unlimited Websites from Aeonfree. With PHP and MySQL and no forced ads on your site.
url: "https://aeonfree.com"
include:
  - _redirects