name: AeonFree
subname: Free And Unlimited Web Hosting with PHP, MySQL and cPanel
description: Get Free Web Hosting with Unlimited Disk Space, Unlimited Bandwidth and Unlimited Websites from Aeonfree. With PHP and MySQL and no forced ads on your free website.
url: "https://aeonfree.com"
include:
  - _redirects
  - ads.txt
  - mywotba4451fda3c08b8c09e7.html
collections:
  articles:
    output: true