name: AeonFree
subname: Free Web Hosting with PHP, MySQL and cPanel
description: Get Free Web Hosting with Unlimited Disk Space, Unlimited Bandwidth and Unlimited Websites from Aeonfree. With PHP and MySQL and no forced ads on your site.
url: "http://127.0.0.1:4000/"
